server:
  port: 12345

spring:
  datasource:
    username: online
    password: root@0nline
    url: jdbc:mysql://1.isdu.online:3306/mmcms?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /
      suffix: .html

  thymeleaf:
    cache: true

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java